# Название воркфлоу
name: Run Linter

# Триггеры для запуска воркфлоу
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Задачи, которые будут выполняться
jobs:
  lint:
    # Имя задачи, которое будет отображаться в интерфейсе GitHub
    name: Run Linter
    # Использовать последнюю версию Ubuntu в качестве операционной системы
    runs-on: ubuntu-latest

    # Шаги выполнения задачи
    steps:
      # Шаг 1: Клонирование вашего репозитория
      - name: Check out code
        uses: actions/checkout@v4

      # Шаг 2: Установка Node.js и кэширование зависимостей Yarn
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      # Шаг 3: Установка основных зависимостей из lock-файла
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # -------------------------------------------------------------------
      # !!! НАЧАЛО БЛОКА ДЛЯ ТЕСТИРОВАНИЯ !!!
      # Установка недостающих зависимостей "на лету" только для проверки воркфлоу.
      # Это не рекомендуется для постоянного использования (production).
      - name: 'TEST-ONLY: Install ESLint dynamically'
        run: yarn add --dev eslint

      - name: 'TEST-ONLY: Install ESLint Next.js config'
        run: yarn add --dev eslint-config-next
      # !!! КОНЕЦ БЛОКА ДЛЯ ТЕСТИРОВАНИЯ !!!
      # -------------------------------------------------------------------

      # Шаг 4: Запуск ESLint
      # Этот шаг теперь должен сработать, так как все зависимости были установлены выше.
      - name: Run ESLint
        run: yarn lint
