# .github/workflows/eslint.yml

name: ESLint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '29 18 * * 4'

jobs:
  lint: # <-- Изменено имя задачи для ясности
    name: Run ESLint Scan
    runs-on: ubuntu-latest
    
    # Добавляем таймаут на случай, если задача зависнет
    timeout-minutes: 10
    
    permissions:
      contents: read
      security-events: write
      actions: read
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      # Изменено: теперь мы запускаем скрипт из package.json
      - name: Run ESLint
        # Запускаем скрипт "lint:ci", который должен быть в package.json
        # Это более гибкий и стандартный подход
        run: npm run lint:ci
        continue-on-error: true

      - name: Upload analysis results to GitHub
        # Добавлено условие: этот шаг выполнится всегда, даже если предыдущий завершился с ошибкой.
        # Это гарантирует загрузку отчета при любых результатах линтинга.
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: eslint-results.sarif
          wait-for-processing: true
